name: 'aws-iam-authenticator tool installer'
description: 'Install a specific version of aws-iam-authenticator binary. Acceptable values are latest or any semantic version string e.g. 0.6.2'
inputs:
   version:
      description: 'Version of aws-iam-authenticator'
      required: true
      default: 'latest'
outputs:
   aws-iam-authenticator-path:
      description: 'Path to the cached aws-iam-authenticator binary'
branding:
   color: 'orange'
runs:
   using: 'node16'
   main: 'lib/index.js'
